export const steel = [
    '100Х13М',
    '110Х18М-ШД',
    '50Х14МФ',
    '40Х10С2М (ЭИ-107)'
]

export const trademark = [
    'WUESTHOF',
    'ЗИК',
    'ЗЛАТКО',
    'ЗОК',
    'АиР'
]

export const knives = [
    {
        "id": 1,
        "name": "Нож универсальный RazorEdge",
        "price": 1899.00,
        "article": "AF0000001952",
        "trademark": "WUESTHOF",
        "series": "Precision Pro",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "100Х13М",
        "rating": 4,
        "description": "Высококачественный универсальный нож с эргономичной рукояткой и лезвием из прочной стали. Подходит для резки овощей, мяса и хлеба."
    },
    {
        "id": 2,
        "name": "Поварской нож ProfiBlade",
        "price": 2999.00,
        "article": "AF0000002953",
        "trademark": "ЗИК",
        "series": "Chef Master",
        "inStock": false,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 50,
        "steel": "110Х18М-ШД",
        "rating": 5,
        "description": "Идеальный нож для профессиональных поваров. Длинное лезвие позволяет легко нарезать крупные куски мяса, рыбы и овощей."
    },
    {
        "id": 3,
        "name": "Santoku Knife",
        "price": 1796.39,
        "article": "AF7678548783",
        "trademark": "WUESTHOF",
        "series": "Grand Prix II",
        "inStock": false,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 0,
        "steel": "100Х13М",
        "rating": 5,
        "description": "This series offers knives with an ergonomic design for comfortable use in the kitchen."
    },
    {
        "id": 4,
        "name": "Utility Knife",
        "price": 1633.8,
        "article": "AF3390657340",
        "trademark": "ЗОК",
        "series": "Classic Ikon",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "100Х13М",
        "rating": 1,
        "description": "This series offers knives with an ergonomic design for comfortable use in the kitchen."
    },
    {
        "id": 5,
        "name": "Boning Knife",
        "price": 1794.67,
        "article": "AF5523841911",
        "trademark": "ЗИК",
        "series": "X Series",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "100Х13М",
        "rating": 4,
        "description": "Made with precision, this knife is ideal for both slicing and chopping with ease."
    },
    {
        "id": 6,
        "name": "Шеф-нож Elite Pro",
        "price": 2699.99,
        "article": "AF6623847293",
        "trademark": "WUESTHOF",
        "series": "Grand Prix II",
        "inStock": false,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 50,
        "steel": "110Х18М-ШД",
        "rating": 5,
        "description": "Профессиональный шеф-нож с долговечным лезвием для нарезки и разделки мяса, рыбы и овощей."
    },
    {
        "id": 7,
        "name": "Нож для рыбалки AquaSharp",
        "price": 1599.50,
        "article": "AF7236586345",
        "trademark": "ЗИК",
        "series": "Fishing Gear",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "100Х13М",
        "rating": 4,
        "description": "Нож для рыболовов, имеет острие, специально разработанное для резки рыбы и мяса."
    },
    {
        "id": 8,
        "name": "Нож для разделки мясных продуктов SharpCut",
        "price": 1999.99,
        "article": "AF9947283947",
        "trademark": "ЗЛАТКО",
        "series": "Butcher's Choice",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 0,
        "steel": "110Х18М-ШД",
        "rating": 4,
        "description": "Нож с острым лезвием, идеально подходящий для разделки мяса и других твердых продуктов."
    },
    {
        "id": 9,
        "name": "Нож для кухни Elite Edge",
        "price": 2499.99,
        "article": "AF2348732904",
        "trademark": "АиР",
        "series": "Chef Select",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "50Х14МФ",
        "rating": 4,
        "description": "Нож с высокой износостойкостью, предназначенный для профессиональной кухни."
    },
    {
        "id": 10,
        "name": "Нож для разделки FlexCut",
        "price": 2199.00,
        "article": "AF1239481920",
        "trademark": "WUESTHOF",
        "series": "Professional Line",
        "inStock": false,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "100Х13М",
        "rating": 3,
        "description": "Идеален для нарезки мяса, рыбы и деликатных продуктов. Отличается прочностью и легкостью в использовании."
    },
    {
        "id": 11,
        "name": "Нож для выживания Adventure Tool",
        "price": 2699.99,
        "article": "AF1829348741",
        "trademark": "ЗИК",
        "series": "Survival Gear",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 50,
        "steel": "40Х10С2М (ЭИ-107)",
        "rating": 5,
        "description": "Компактный и надежный нож для выживания в условиях дикой природы."
    },
    {
        "id": 12,
        "name": "Охотничий нож WildHunter",
        "price": 2799.00,
        "article": "AF7293849201",
        "trademark": "ЗЛАТКО",
        "series": "Wild Series",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 0,
        "steel": "50Х14МФ",
        "rating": 4,
        "description": "Прочный нож для охотников, отлично подходит для разделки мяса и работы в сложных условиях."
    },
    {
        "id": 13,
        "name": "Кухонный нож MasterChef",
        "price": 2299.50,
        "article": "AF4938493045",
        "trademark": "АиР",
        "series": "Professional Cut",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "100Х13М",
        "rating": 5,
        "description": "Нож для опытных поваров, с острым лезвием и устойчивым к износу покрытием."
    },
    {
        "id": 14,
        "name": "Нож для резки хлеба BreadMaster",
        "price": 1599.00,
        "article": "AF3928401938",
        "trademark": "ЗИК",
        "series": "Kitchen Essentials",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 50,
        "steel": "40Х10С2М (ЭИ-107)",
        "rating": 4,
        "description": "Отличный нож для нарезки хлеба и других мягких продуктов с плотной коркой."
    },
    {
        "id": 15,
        "name": "Нож для морепродуктов OceanCut",
        "price": 2199.99,
        "article": "AF3849203947",
        "trademark": "WUESTHOF",
        "series": "Marine Tools",
        "inStock": false,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "50Х14МФ",
        "rating": 5,
        "description": "Прочные ножи с острым лезвием, предназначенные для разделки рыбы и морепродуктов."
    },
    {
        "id": 16,
        "name": "Нож для овощей Veggie Master",
        "price": 1599.50,
        "article": "AF4820398473",
        "trademark": "ЗИК",
        "series": "Home Kitchen",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "100Х13М",
        "rating": 4,
        "description": "Отличный нож для нарезки овощей и фруктов с удобной рукояткой и острым лезвием."
    },
    {
        "id": 17,
        "name": "Нож для резки мяса SteakMaster",
        "price": 2399.00,
        "article": "AF1839203847",
        "trademark": "АиР",
        "series": "Gourmet Collection",
        "inStock": false,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "110Х18М-ШД",
        "rating": 5,
        "description": "Нож для профессиональной нарезки стейков и других мясных продуктов. Обеспечивает точность и легкость в работе."
    },
    {
        "id": 18,
        "name": "Нож для разделки BoneBreaker",
        "price": 2999.50,
        "article": "AF3847388291",
        "trademark": "ЗЛАТКО",
        "series": "Heavy Duty",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 50,
        "steel": "40Х10С2М (ЭИ-107)",
        "rating": 5,
        "description": "Мощный нож с толстым лезвием для работы с твердыми костями и другими трудными продуктами."
    },
    {
        "id": 19,
        "name": "Нож для рыбы FishSharp",
        "price": 1899.99,
        "article": "AF2748392039",
        "trademark": "WUESTHOF",
        "series": "Marine Tools",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "100Х13М",
        "rating": 5,
        "description": "Отличный нож для нарезки рыбы и морепродуктов. Лезвие сохраняет свою остроту даже при длительном использовании."
    },
    {
        "id": 20,
        "name": "Нож для хлеба Baker's Edge",
        "price": 1799.00,
        "article": "AF7482739402",
        "trademark": "ЗИК",
        "series": "Culinary Classics",
        "inStock": false,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 0,
        "steel": "50Х14МФ",
        "rating": 4,
        "description": "Идеален для нарезки хлеба с мягким мякишем и хрустящей коркой. Остриё сохраняет свою остроту длительное время."
    },
    {
        "id": 21,
        "name": "Нож для разделки FlexPro",
        "price": 2499.00,
        "article": "AF4938392839",
        "trademark": "АиР",
        "series": "Precision Line",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "40Х10С2М (ЭИ-107)",
        "rating": 5,
        "description": "Мощный нож с гибким лезвием для удобной разделки мяса и рыбы. Отличная устойчивость к износу."
    },
    {
        "id": 22,
        "name": "Шеф-нож Premium Cook",
        "price": 2799.99,
        "article": "AF2848293842",
        "trademark": "ЗЛАТКО",
        "series": "Chef's Choice",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "100Х13М",
        "rating": 5,
        "description": "Профессиональный шеф-нож с идеально заточенным лезвием для работы с мясом, рыбой и овощами."
    },
    {
        "id": 23,
        "name": "Многофункциональный нож MultiEdge",
        "price": 2199.00,
        "article": "AF3294872498",
        "trademark": "АиР",
        "series": "Utility Tools",
        "inStock": false,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 50,
        "steel": "50Х14МФ",
        "rating": 4,
        "description": "Многофункциональный нож с возможностью использования для различных задач на кухне и в походах."
    },
    {
        "id": 24,
        "name": "Нож для обработки овощей VeggiePro",
        "price": 1699.50,
        "article": "AF2837463201",
        "trademark": "ЗИК",
        "series": "Fresh Cut",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "100Х13М",
        "rating": 5,
        "description": "Специально предназначен для нарезки овощей, с тонким и острым лезвием для точной работы."
    },
    {
        "id": 25,
        "name": "Нож для хлеба BreadSharp",
        "price": 1799.00,
        "article": "AF4938293845",
        "trademark": "WUESTHOF",
        "series": "Classic Line",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 50,
        "steel": "110Х18М-ШД",
        "rating": 5,
        "description": "Отличный нож для разделки хлеба с хрустящей коркой и мягким мякишем. Удобен в использовании и долговечен."
    },
    {
        "id": 26,
        "name": "Шеф-нож EliteCut",
        "price": 2999.99,
        "article": "AF1029384756",
        "trademark": "ЗИК",
        "series": "Pro Chef",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "50Х14МФ",
        "rating": 5,
        "description": "Профессиональный шеф-нож с острым лезвием для точной нарезки. Идеален для нарезки мяса, рыбы и овощей."
    },
    {
        "id": 27,
        "name": "Нож для очистки FruitBlade",
        "price": 1499.00,
        "article": "AF7382916472",
        "trademark": "АиР",
        "series": "Fruit Tools",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "100Х13М",
        "rating": 4,
        "description": "Удобный нож для чистки фруктов и овощей с острым и гибким лезвием."
    },
    {
        "id": 28,
        "name": "Нож для рыбы FishMaster",
        "price": 1899.99,
        "article": "AF3847583923",
        "trademark": "ЗЛАТКО",
        "series": "Marine Tools",
        "inStock": false,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 50,
        "steel": "40Х10С2М (ЭИ-107)",
        "rating": 5,
        "description": "Идеальный нож для работы с рыбой. Лезвие сохраняет свою остроту при длительном использовании."
    },
    {
        "id": 29,
        "name": "Нож для разделки мясо MeatPro",
        "price": 2699.00,
        "article": "AF4975738291",
        "trademark": "WUESTHOF",
        "series": "Premium Series",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "110Х18М-ШД",
        "rating": 4,
        "description": "Высококачественный нож для разделки мяса с длинным лезвием и удобной рукояткой."
    },
    {
        "id": 30,
        "name": "Охотничий нож WildHunter",
        "price": 2999.00,
        "article": "AF7283649271",
        "trademark": "ЗИК",
        "series": "Wild Adventure",
        "inStock": false,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "100Х13М",
        "rating": 5,
        "description": "Прочный нож с надежной рукояткой для охоты. Лезвие идеально подходит для работы в полевых условиях."
    },
    {
        "id": 31,
        "name": "Многофункциональный нож UtilityMax",
        "price": 2299.50,
        "article": "AF5647382847",
        "trademark": "АиР",
        "series": "Survival Tools",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "50Х14МФ",
        "rating": 4,
        "description": "Многофункциональный нож с набором инструментов для различных ситуаций в походах и на природе."
    },
    {
        "id": 32,
        "name": "Нож для хлеба Baker's Edge",
        "price": 1799.00,
        "article": "AF3928472837",
        "trademark": "ЗЛАТКО",
        "series": "Baking Series",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 0,
        "steel": "40Х10С2М (ЭИ-107)",
        "rating": 5,
        "description": "Специализированный нож для нарезки хлеба. Лезвие позволяет легко разрезать хлеб с хрустящей коркой."
    },
    {
        "id": 33,
        "name": "Шеф-нож ProCut",
        "price": 2999.50,
        "article": "AF5738292847",
        "trademark": "WUESTHOF",
        "series": "Professional Line",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "50Х14МФ",
        "rating": 5,
        "description": "Профессиональный шеф-нож для нарезки мяса и овощей с оптимальной длиной лезвия."
    },
    {
        "id": 34,
        "name": "Нож для разделки кости BoneCutter",
        "price": 2599.00,
        "article": "AF3947382736",
        "trademark": "ЗИК",
        "series": "Hunter's Series",
        "inStock": false,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "40Х10С2М (ЭИ-107)",
        "rating": 4,
        "description": "Нож для работы с твердыми костями и разделки мяса. Идеален для использования в условиях охоты."
    },
    {
        "id": 35,
        "name": "Нож для рыбалки SeaMaster",
        "price": 1899.00,
        "article": "AF2837461827",
        "trademark": "АиР",
        "series": "Fishing Gear",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "110Х18М-ШД",
        "rating": 5,
        "description": "Идеальный нож для рыболовов с прочным лезвием и удобной рукояткой. Лезвие сохраняет остроту при длительном использовании."
    },
    {
        "id": 36,
        "name": "Нож для готования Chef Pro",
        "price": 2899.99,
        "article": "AF3928472928",
        "trademark": "ЗИК",
        "series": "Gourmet Series",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "50Х14МФ",
        "rating": 4,
        "description": "Универсальный шеф-нож, идеально подходящий для нарезки и подготовки продуктов. Лезвие устойчиво к износу и ржавчине."
    },
    {
        "id": 37,
        "name": "Нож для слайсинга SliceMaster",
        "price": 2499.00,
        "article": "AF9283748129",
        "trademark": "АиР",
        "series": "Precision Slicing",
        "inStock": false,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 50,
        "steel": "100Х13М",
        "rating": 4,
        "description": "Тонкое и острое лезвие, которое идеально подходит для слайсинга мяса и рыбы. Прочный и надежный инструмент."
    },
    {
        "id": 38,
        "name": "Нож для разделки рыбы FishCut",
        "price": 2199.50,
        "article": "AF7283949201",
        "trademark": "ЗЛАТКО",
        "series": "Fishmaster",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "50Х14МФ",
        "rating": 5,
        "description": "Идеальный нож для рыбалки с гибким лезвием, которое позволяет точно разделать рыбу, не повреждая ее."
    },
    {
        "id": 39,
        "name": "Охотничий нож Ranger",
        "price": 2799.99,
        "article": "AF9483740123",
        "trademark": "ЗИК",
        "series": "Hunting Tools",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "40Х10С2М (ЭИ-107)",
        "rating": 4,
        "description": "Охотничий нож с прочным лезвием и рукояткой из высококачественных материалов. Отлично подходит для работы в полевых условиях."
    },
    {
        "id": 40,
        "name": "Шеф-нож Culinary Master",
        "price": 3099.00,
        "article": "AF9483741234",
        "trademark": "WUESTHOF",
        "series": "Classic Series",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "100Х13М",
        "rating": 5,
        "description": "Качественный шеф-нож с идеальным балансом и острым лезвием, что позволяет легко нарезать продукты."
    },
    {
        "id": 41,
        "name": "Нож для выживания Survival Pro",
        "price": 2999.50,
        "article": "AF7382738473",
        "trademark": "ЗЛАТКО",
        "series": "Tactical Line",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 50,
        "steel": "110Х18М-ШД",
        "rating": 5,
        "description": "Нож для выживания с прочным лезвием и удобной рукояткой для экстремальных условий."
    },
    {
        "id": 42,
        "name": "Нож для разделки мяса Meat Cleaver",
        "price": 2599.99,
        "article": "AF7382948732",
        "trademark": "АиР",
        "series": "Heavy Duty",
        "inStock": false,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "50Х14МФ",
        "rating": 4,
        "description": "Мощный нож для разделки крупного мяса с толстым лезвием и прочной рукояткой."
    },
    {
        "id": 43,
        "name": "Нож для карвинга CarveMaster",
        "price": 2699.00,
        "article": "AF7382918372",
        "trademark": "ЗИК",
        "series": "Artisan Series",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "40Х10С2М (ЭИ-107)",
        "rating": 5,
        "description": "Прекрасный нож для резьбы по мясу и карвинга. Лезвие обладает исключительной остротой."
    },
    {
        "id": 44,
        "name": "Шеф-нож Grand Cuisine",
        "price": 3199.00,
        "article": "AF7382738241",
        "trademark": "WUESTHOF",
        "series": "Elite Series",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 50,
        "steel": "100Х13М",
        "rating": 4,
        "description": "Профессиональный шеф-нож с уникальной геометрией лезвия и превосходной остротой."
    },
    {
        "id": 45,
        "name": "Карманный нож PocketPro",
        "price": 1399.00,
        "article": "AF7382748472",
        "trademark": "ЗЛАТКО",
        "series": "Everyday Carry",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "50Х14МФ",
        "rating": 5,
        "description": "Компактный и легкий нож для повседневного ношения с устойчивым лезвием."
    },
    {
        "id": 46,
        "name": "Охотничий нож Outlander",
        "price": 2899.00,
        "article": "AF9283749734",
        "trademark": "ЗИК",
        "series": "Hunter Series",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 30,
        "steel": "50Х14МФ",
        "rating": 4,
        "description": "Нож с прочным лезвием, предназначенный для использования в сложных природных условиях. Прекрасно подходит для охоты и активного отдыха."
    },
    {
        "id": 47,
        "name": "Шеф-нож Royal Chef",
        "price": 3099.50,
        "article": "AF7283947283",
        "trademark": "АиР",
        "series": "Gourmet Collection",
        "inStock": false,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 50,
        "steel": "100Х13М",
        "rating": 5,
        "description": "Профессиональный шеф-нож с идеальным балансом для точных нарезок. Лезвие выдерживает продолжительную работу без заточки."
    },
    {
        "id": 48,
        "name": "Нож для рыбалки Fisherman",
        "price": 2399.99,
        "article": "AF9283749247",
        "trademark": "ЗЛАТКО",
        "series": "Outdoor Essentials",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "50Х14МФ",
        "rating": 5,
        "description": "Нож для рыбалки с эргономичной рукояткой и стойким лезвием, идеально подходящий для разделки рыбы и других рыболовных задач."
    },
    {
        "id": 49,
        "name": "Нож для выживания Ranger Elite",
        "price": 3199.00,
        "article": "AF7382917363",
        "trademark": "ЗИК",
        "series": "Survival Series",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 50,
        "steel": "110Х18М-ШД",
        "rating": 4,
        "description": "Нож с высокой прочностью и особым дизайном, предназначенный для выживания в экстремальных условиях. Отличается долговечностью и устойчивостью к нагрузкам."
    },
    {
        "id": 50,
        "name": "Туристический нож Adventure Trail",
        "price": 2499.99,
        "article": "AF9283748219",
        "trademark": "АиР",
        "series": "Explorer Gear",
        "inStock": false,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 40,
        "steel": "100Х13М",
        "rating": 4,
        "description": "Компактный и удобный нож для туристов и путешественников. С этим ножом легко справиться с любыми задачами в походах."
    },
    {
        "id": 51,
        "name": "Шеф-нож Culinary Precision",
        "price": 2799.00,
        "article": "AF9283747632",
        "trademark": "WUESTHOF",
        "series": "Professional Line",
        "inStock": true,
        "image": "1.jpg",
        "images": ["2.jpg", "3.jpg", "4.jpg", "5.jpg"],
        "discount": 50,
        "steel": "100Х13М",
        "rating": 5,
        "description": "Нож с точной геометрией лезвия, предназначенный для профессиональных кулинаров. Отличается высоким качеством и длительным сроком службы."
    }
];
